# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0dfe5ab3c1c5b92f714820e73fce11c8"
name = "OneGuard"
handle = "oneguard-app"
application_url = "https://endorsement-hourly-glass-over.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-99c03ff2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://endorsement-hourly-glass-over.trycloudflare.com/auth/callback",
  "https://endorsement-hourly-glass-over.trycloudflare.com/auth/shopify/callback",
  "https://endorsement-hourly-glass-over.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order-create"

[app_proxy]
url = "https://endorsement-hourly-glass-over.trycloudflare.com/app/proxy"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
