# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0dfe5ab3c1c5b92f714820e73fce11c8"
name = "OneGuard"
handle = "oneguard"
application_url = "https://likewise-bet-pregnancy-appearance.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-99c03ff2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://likewise-bet-pregnancy-appearance.trycloudflare.com/auth/callback",
  "https://likewise-bet-pregnancy-appearance.trycloudflare.com/auth/shopify/callback",
  "https://likewise-bet-pregnancy-appearance.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
